#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct CommonModelsDestinytwoCoreSettings {
    pub badges_root_node: !,
    pub legacy_seals_root_node_hash: !,
    pub active_seals_root_node_hash: !,
    pub active_triumphs_root_node_hash: !,
    pub medals_root_node_hash: !,
    pub crafting_root_node_hash: !,
    pub exotic_catalysts_root_node_hash: !,
    pub guardian_rank_constants_hash: !,
    pub ammo_type_special_icon: !,
    pub current_season_hash: !,
    pub lore_root_node_hash: !,
    pub guardian_ranks_root_node_hash: !,
    pub seasonal_challenges_presentation_node_hash: !,
    pub loadout_constants_hash: !,
    pub collection_root_node: !,
    pub current_seasonal_artifact_hash: !,
    pub ammo_type_primary_icon: !,
    pub metrics_root_node: !,
    pub medals_root_node: !,
    pub ammo_type_heavy_icon: !,
    pub undiscovered_collectible_image: !,
    pub records_root_node: !,
    pub legacy_triumphs_root_node_hash: !,
}
