#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct DestinyDefinitionsDestinyInventoryItemDefinition {
    pub icon_watermark_shelved: !,
    pub item_type_display_name: !,
    pub ui_item_display_style: !,
    pub allow_actions: !,
    pub default_damage_type_hash: !,
    pub item_sub_type: !,
    pub equippable: !,
    pub default_damage_type: !,
    pub item_type: !,
    pub breaker_type_hash: !,
    pub special_item_type: !,
    pub lore_hash: !,
    pub hash: !,
    pub tooltip_style: !,
    pub flavor_text: !,
    pub is_wrapper: !,
    pub secondary_special: !,
    pub season_hash: !,
    pub collectible_hash: !,
    pub secondary_overlay: !,
    pub screenshot: !,
    pub summary_item_hash: !,
    pub index: !,
    pub secondary_icon: !,
    pub non_transferrable: !,
    pub does_postmaster_pull_have_side_effects: !,
    pub breaker_type: !,
    pub icon_watermark: !,
    pub item_type_and_tier_display_name: !,
    pub display_source: !,
    pub class_type: !,
    pub emblem_objective_hash: !,
    pub redacted: !,
}
