#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct DestinyDefinitionsDestinyVendorItemDefinition {
    pub maximum_level: !,
    pub sort_value: !,
    pub display_category_index: !,
    pub purchasable_scope: !,
    pub is_offer: !,
    pub unpurchasable: !,
    pub quantity: !,
    pub item_hash: !,
    pub original_category_index: !,
    pub visibility_scope: !,
    pub inventory_bucket_hash: !,
    pub refund_policy: !,
    pub expiration_tooltip: !,
    pub is_crm: !,
    pub refund_time_limit: !,
    pub vendor_item_index: !,
    pub display_category: !,
    pub category_index: !,
    pub exclusivity: !,
    pub minimum_level: !,
}
