#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct DestinyEntitiesCharactersDestinyCharacterComponent {
    pub class_type: !,
    pub gender_type: !,
    pub light: !,
    pub emblem_background_path: !,
    pub emblem_hash: !,
    pub membership_type: !,
    pub base_character_level: !,
    pub character_id: !,
    pub class_hash: !,
    pub race_type: !,
    pub percent_to_next_level: !,
    pub title_record_hash: !,
    pub emblem_path: !,
    pub membership_id: !,
    pub minutes_played_this_session: !,
    pub race_hash: !,
    pub gender_hash: !,
    pub date_last_played: !,
    pub minutes_played_total: !,
}
