#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct FireteamFireteamSummary {
    pub date_created: !,
    pub owner_highest_lifetime_guardian_rank_snapshot: !,
    pub date_player_modified: !,
    pub scheduled_time: !,
    pub title_before_moderation: !,
    pub locale: !,
    pub owner_total_commendation_score_snapshot: !,
    pub alternate_slot_count: !,
    pub title: !,
    pub date_modified: !,
    pub available_player_slot_count: !,
    pub fireteam_id: !,
    pub is_immediate: !,
    pub activity_type: !,
    pub owner_membership_id: !,
    pub is_valid: !,
    pub owner_current_guardian_rank_snapshot: !,
    pub available_alternate_slot_count: !,
    pub player_slot_count: !,
    pub is_public: !,
    pub group_id: !,
    pub platform: !,
}
