#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct GroupsVtwoGroupVtwo {
    pub creation_date: !,
    pub banner_path: !,
    pub avatar_path: !,
    pub ban_expire_date: !,
    pub homepage: !,
    pub motto: !,
    pub avatar_image_index: !,
    pub default_publicity: !,
    pub theme: !,
    pub conversation_id: !,
    pub locale: !,
    pub group_type: !,
    pub membership_option: !,
    pub enable_invitation_messaging_for_admins: !,
    pub about: !,
    pub allow_chat: !,
    pub is_default_post_public: !,
    pub membership_id_created: !,
    pub chat_security: !,
    pub name: !,
    pub modification_date: !,
    pub member_count: !,
    pub is_public: !,
    pub is_public_topic_admin_only: !,
    pub group_id: !,
}
