#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct UserGeneralUser {
    pub about: !,
    pub show_activity: !,
    pub profile_picture_path: !,
    pub profile_picture_wide_path: !,
    pub first_access: !,
    pub psn_display_name: !,
    pub profile_theme_name: !,
    pub profile_ban_expire: !,
    pub locale: !,
    pub cached_bungie_global_display_name: !,
    pub is_deleted: !,
    pub fb_display_name: !,
    pub status_date: !,
    pub stadia_display_name: !,
    pub xbox_display_name: !,
    pub last_ban_report_id: !,
    pub blizzard_display_name: !,
    pub unique_name: !,
    pub locale_inherit_default: !,
    pub membership_id: !,
    pub user_title: !,
    pub cached_bungie_global_display_name_code: !,
    pub last_update: !,
    pub normalized_name: !,
    pub profile_picture: !,
    pub steam_display_name: !,
    pub display_name: !,
    pub show_group_messaging: !,
    pub user_title_display: !,
    pub egs_display_name: !,
    pub legacy_portal_uid: !,
    pub profile_theme: !,
    pub twitch_display_name: !,
    pub success_message_flags: !,
    pub status_text: !,
}
