#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct LocalizedNamesDto {
    pub en_gb: !,
    pub id_id: !,
    pub pt_br: !,
    pub vi_vn: !,
    pub es_es: !,
    pub ru_ru: !,
    pub th_th: !,
    pub fr_fr: !,
    pub ja_jp: !,
    pub ko_kr: !,
    pub tr_tr: !,
    pub es_mx: !,
    pub it_it: !,
    pub ar_ae: !,
    pub de_de: !,
    pub pl_pl: !,
    pub en_us: !,
    pub zh_tw: !,
    pub zh_cn: !,
}
