#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct MatchTimelineInfoFrameEvent {
    pub killer_team_id: !,
    pub gold_gain: !,
    pub shutdown_bounty: !,
    pub multi_kill_length: !,
    pub skill_slot: !,
    pub game_id: !,
    pub kill_streak_length: !,
    pub type: !,
    pub team_id: !,
    pub real_timestamp: !,
    pub building_type: !,
    pub actual_start_time: !,
    pub level_up_type: !,
    pub monster_sub_type: !,
    pub monster_type: !,
    pub transform_type: !,
    pub timestamp: !,
    pub bounty: !,
    pub after_id: !,
    pub killer_id: !,
    pub ward_type: !,
    pub tower_type: !,
    pub item_id: !,
    pub kill_type: !,
    pub before_id: !,
    pub winning_team: !,
    pub name: !,
    pub participant_id: !,
    pub creator_id: !,
    pub victim_id: !,
    pub lane_type: !,
    pub level: !,
}
