#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct MatchTimelineInfoFrameParticipantFrameChampionStats {
    pub bonus_magic_pen_percent: !,
    pub health_regen: !,
    pub power: !,
    pub cooldown_reduction: !,
    pub power_regen: !,
    pub ability_haste: !,
    pub attack_damage: !,
    pub armor_pen_percent: !,
    pub cc_reduction: !,
    pub magic_pen: !,
    pub bonus_armor_pen_percent: !,
    pub movement_speed: !,
    pub ability_power: !,
    pub attack_speed: !,
    pub spell_vamp: !,
    pub health: !,
    pub health_max: !,
    pub lifesteal: !,
    pub magic_pen_percent: !,
    pub power_max: !,
    pub armor: !,
    pub armor_pen: !,
    pub magic_resist: !,
    pub omnivamp: !,
    pub physical_vamp: !,
}
