[package]
name = "sw4rm-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
serde_yaml = "0.9.31"

resolve-core = { version = "=0.1.0", path = "resolve-core" }
resolve-macro = { version = "=0.1.0", path = "resolve-macro" }

[workspace]
members = ["resolve-core", "resolve-macro"]