#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct GuildWithCountsResponse {
    pub systemchannelflags: !,
    pub premiumtier: !,
    pub preferredlocale: !,
    pub premiumprogressbarenabled: !,
    pub splash: !,
    pub maxmembers: !,
    pub afktimeout: !,
    pub ownerid: !,
    pub banner: !,
    pub maxvideochannelusers: !,
    pub approximatepresencecount: !,
    pub id: !,
    pub widgetenabled: !,
    pub verificationlevel: !,
    pub icon: !,
    pub region: !,
    pub discoverysplash: !,
    pub mfalevel: !,
    pub nsfw: !,
    pub description: !,
    pub name: !,
    pub vanityurlcode: !,
    pub homeheader: !,
    pub premiumsubscriptioncount: !,
    pub approximatemembercount: !,
    pub defaultmessagenotifications: !,
    pub maxstagevideochannelusers: !,
    pub explicitcontentfilter: !,
    pub maxpresences: !,
    pub nsfwlevel: !,
}
